spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RmilaXcode/microservices-demo
          search-paths: config-repo
server:
  port: 8888
